
ORG 00H
LJMP MAIN

DELAY:
		USING 0
		PUSH ACC
		PUSH AR0
		MOV R0,#81H         ;INDIRECT READ FROM MEMORY LOCATION 81H
		MOV A,@R0
		CPL A    			;COMPLEMENT OF A
		ADD A,#01    		;ADD 1 TO MAKE IT 2'S COMPLEMENT
		MOV TL0,A          
		INC R0              ;CARRY FLAG IS NOT AFFECTED BY INC
		MOV A,@R0
		CPL A               ;COMPLEMENT OF ANOTHER BYTE
		ADDC A,#00H         ;WILL ADD CARRY IF GENERATED FROM LOWER BYTE
		MOV TH0,A      
						;2'S COMPLEMENT OF THE 16BIT NO. IS NOW STORED IN T0
		MOV TMOD,#01
		SETB TR0             ;ENABLE TIMER 0
START_COUNT:
		JNB TF0,START_COUNT    ;Jump if Bit Not Set
		CLR TR0              ;STOP TIMER
		CLR TF0              ;CLEAR OVERFLOW BIT
		POP AR0
		POP ACC
RET

MAIN:
	USING 0
	MOV R0,#81H
	MOV @R0,#050H				;MAX N = 65,536   FFFFH
	INC R0						;SETTING N = 50,000  FOR GETTING DELAY = 25MSEC
	MOV @R0,#0C3H        		;DELAY CORRESPONDING TO 3EFFH WOULD BE GENERATED
	
	
	LED_BLINK:             	    ;TO SHOW ON LED
		MOV 50H,#40
		MOV 51H,#40
		
		MOV P1,#0F0H
		LOOP:
		LCALL DELAY 
		DJNZ 50H,LOOP
		
		MOV P1,#0H
		LOOP2:
		LCALL DELAY
		DJNZ 51H,LOOP2
		
		SJMP LED_BLINK
	STOP: SJMP STOP

END